---
- name: Create admin docroot
  file: path={{ wp_doc_root }}/admin state=directory owner={{ web_user }} group={{ web_group }}
  tags: [ 'admin' ]

- name: Stub out index
  template: src=index.php dest={{ wp_doc_root }}/admin/index.php owner={{ web_user }} group={{ web_group }}
  tags: [ 'admin' ]

- name: Set up admin
  template: src=etc/nginx/conf.d/admin.conf dest=/etc/nginx/conf.d/admin.conf owner=root group=root mode=0644
  notify: nginx reload
  tags: [ 'admin' ]

#
# phpMyAdmin Setup
#
- name: Ensure phpMyAdmin directory exists
  file: path={{ wp_doc_root }}/admin/phpmyadmin state=directory owner={{ web_user }} group={{ web_group }}
  tags: [ 'admin', 'phpmyadmin' ]

- name: Download phpMyAdmin
  get_url: url=https://s3-us-west-2.amazonaws.com/com.wpengine.labs-packages/phpMyAdmin-{{ phpmyadmin_version }}.zip dest=/tmp/phpMyAdmin-{{ phpmyadmin_version }}.zip
  tags: [ 'admin', 'phpmyadmin' ]

- name: Extract phpMyAdmin
  unarchive: src=/tmp/phpMyAdmin-{{ phpmyadmin_version }}.zip dest=/tmp copy=no owner={{ web_user }} group={{ web_group }} creates=/tmp/phpMyAdmin-{{ phpmyadmin_version }}
  tags: [ 'admin', 'phpmyadmin' ]

- name: Sync phpMyAdmin
  synchronize: src=/tmp/phpMyAdmin-{{ phpmyadmin_version }}/ dest={{ wp_doc_root }}/admin/phpmyadmin/ group=no owner=no
  tags: [ 'admin', 'phpmyadmin' ]

- name: Configure phpMyAdmin
  template: src=phpmyadminconfig.php dest={{ wp_doc_root }}/admin/phpmyadmin/config.inc.php group={{ web_group }} owner={{ web_user }}
  tags: ['admin', 'phpmyadmin' ]

#
# phpMemcachedAdmin setup
#
- name: Check whether pMA is a Git checkout
  stat:
    path: "{{ wp_doc_root }}/admin/phpmemcachedadmin/.git"
  register: pma_git_dir

- name: Nuke pMA install if not a Git checkout
  file:
    path: "{{ wp_doc_root }}/admin/phpmemcachedadmin"
    state: absent
  when: pma_git_dir.stat.isdir is not defined
  
- name: Ensure phpMemcachedAdmin directory exists
  file:
    path: "{{ wp_doc_root }}/admin/phpmemcachedadmin"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
  tags: [ 'admin', 'phpmemcachedadmin' ]

- name: Download phpMemcachedAdmin
  git:
    repo: https://github.com/wp-cloud/phpmemcacheadmin.git
    dest: "{{ wp_doc_root }}/admin/phpmemcachedadmin"
    update: no
    accept_hostkey: yes
  tags: [ 'admin', 'phpmemcachedadmin' ]

#
# PimpMyLogs setup
#
- name: Ensure PML directory exists
  file: path={{ wp_doc_root }}/admin/logs state=directory owner={{ web_user }} group={{ web_group }}
  tags: [ 'admin', 'pimpmylog' ]

- name: Download PML
  git: repo=git://github.com/potsky/PimpMyLog.git dest={{ wp_doc_root }}/admin/logs update=no accept_hostkey=yes
  tags: [ 'admin', 'pimpmylog' ]

- name: Configure PML
  template: src=pimpmylog.config.user.php dest={{ wp_doc_root }}/admin/logs/config.user.php group={{ web_group }} owner={{ web_user }} mode=0444
  tags: [ 'admin', 'pimpmylog' ]

- name: Create custom user config dir
  file: path={{ wp_doc_root }}/admin/logs/config.user.d state=directory owner={{ web_user }} group={{ web_group }}
  tags: [ 'admin', 'pimpmylog' ]

#
# MailHog setup
#
- name: Ensure mailhog directory exists
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  tags: [ 'admin', 'mailhog' ]

- name: Download MailHog
  get_url:
    url: "{{ mailhog_binary_url }}"
    dest: "{{ mailhog_install_dir }}/mailhog"
    owner: root
    group: root
    mode: 0755
  tags: [ 'admin', 'mailhog' ]

- name: Install mailhog init script
  copy:
    src: mailhog_init
    dest: /etc/init.d/mailhog
    owner: root
    group: root
    mode: 0755
  tags: [ 'admin', 'mailhog' ]

- name: Ensure mailhog is enabled and will start on boot.
  service:
    name: mailhog
    state: started
    enabled: yes
  tags: [ 'admin', 'mailhog' ]

- name: Install sSMTP.
  apt: pkg=ssmtp state=installed
  tags: [ 'admin', 'mailhog' ]

- name: Copy sSMTP configuration.
  template:
    src: etc/ssmtp/ssmtp.conf
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644
  tags: [ 'admin', 'mailhog' ]

- name: Set up Mailhog virtualhost
  copy:
    src: etc/nginx/conf.d/mail.conf
    dest: /etc/nginx/conf.d/mail.conf
    owner: root
    group: root
    mode: 0644
  notify: nginx reload
  tags: [ 'admin', 'mailhog' ]

- name: Set up PHP sendmail
  ini_file:
    dest: "{{ item }}"
    section: "mail function"
    option: sendmail_path
    value: "/usr/sbin/ssmtp -t"
  with_items:
      - /etc/php5/fpm/php.ini
      - /etc/php5/cli/php.ini

# Webgrind setup
- name: Ensure Webgrind directory exists
  file:
    path: "{{ wp_doc_root }}/admin/webgrind"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
  tags: [ 'admin', 'webgrind' ]

- name: Download Webgrind
  git:
    repo: "git://github.com/jokkedk/webgrind.git"
    dest: "{{ wp_doc_root }}/admin/webgrind"
    update: no
    accept_hostkey: yes
  tags: [ 'admin', 'webgrind' ]

#
# Info Template setup
#
- name: Setup phpinfo.php
  template: src=phpinfo.php dest={{ wp_doc_root }}/admin/phpinfo.php owner={{ web_user }} group={{ web_group }}
  tags: [ 'admin', 'info' ]

- name: Setup hhvminfo.php
  template: src=hhvminfo.php dest={{ wp_doc_root }}/admin/hhvminfo.php owner={{ web_user }} group={{ web_group }}
  tags: [ 'admin', 'info' ]
