---
- name: "Set facts for PHP run"
  set_fact:
    wpbackend: php
  tags: [ 'wpsites' ]

- name: "Provision {{ item.key }} PHP virtualhost"
  template:
    src: etc/nginx/conf.d/wpsites.conf
    dest: /etc/nginx/conf.d/{{ item.key }}.conf
    owner: root
    group: root
    mode: 0644
  with_dict: wpsites
  tags: [ 'wpsites' ]

- name: "Set facts for HHVM run"
  set_fact:
    wpbackend: hhvm
  tags: [ 'wpsites' ]

- name: "Provision {{ item.key }} hhvm virtualhost"
  template:
    src: etc/nginx/conf.d/wpsites.conf
    dest: /etc/nginx/conf.d/hhvm-{{ item.key }}.conf
    owner: root
    group: root
    mode: 0644
  with_dict: wpsites
  tags: [ 'wpsites' ]
